# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f16a44222d4a44b1ca785399a5ad1323fa49ed4c77f71e69beef92440b6171fd46048810d07a823475b8201b72b8593a198979cfe5ed6ed8936fec038b622965

test:
  secret_key_base: fbd5a4393fbe5c37a5faa69a831ed88e23d434147503b1d01b1bb911ce313b053d50b3acdd2f96e8faab6cae1fefc616c223ff87f6359eddc6ad27525237077b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
